export const movies = [
  {
    vote_count: 74,
    id: 437557,
    video: false,
    vote_average: 6.3,
    title: "Blockers",
    popularity: 34.345866,
    poster_path: "/cx0LpfM6Drla8uzFfMT09uqKPRu.jpg",
    original_language: "en",
    original_title: "Blockers",
    genre_ids: [35],
    backdrop_path: "/bStCGzVYFrKxtOyThKkqgI8gjgE.jpg",
    adult: false,
    overview:
      "When three parents discover their daughters’ pact to lose their virginity at prom, they launch a covert one-night operation to stop the teens from sealing the deal.",
    release_date: "2018-03-30"
  },
  {
    vote_count: 2,
    id: 454619,
    video: false,
    vote_average: 0,
    title: "Overboard",
    popularity: 28.400763,
    poster_path: "/gaHknuun1VPPugkTsSfB8PejKVg.jpg",
    original_language: "en",
    original_title: "Overboard",
    genre_ids: [10749, 35],
    backdrop_path: "/yCfXPtYz1CtPw4bbjAZ8xwXenNS.jpg",
    adult: false,
    overview:
      "A spoiled, wealthy yacht owner is thrown overboard and becomes the target of revenge from his mistreated employee. A remake of the 1987 comedy.",
    release_date: "2018-05-03"
  },
  {
    vote_count: 1,
    id: 385332,
    video: false,
    vote_average: 0,
    title: "Terminal",
    popularity: 7.062166,
    poster_path: "/rclxSjQ85P5c1W1esvgXlpql36R.jpg",
    original_language: "en",
    original_title: "Terminal",
    genre_ids: [53, 18],
    backdrop_path: "/k00wJ1PiF3Q1439zEQKIfZxcN3M.jpg",
    adult: false,
    overview:
      'In the dark heart of a sprawling, anonymous city, "Terminal" follows the twisting tales of two assassins carrying out a sinister mission, a teacher battling a fatal illness, an enigmatic janitor and a curious waitress leading a dangerous double life. Murderous consequences unravel in the dead of night as their lives all intertwine at the hands of a mysterious criminal mastermind hell-bent on revenge.',
    release_date: "2018-05-11"
  },
  {
    vote_count: 2,
    id: 354279,
    video: false,
    vote_average: 8,
    title: "Charming",
    popularity: 5.331591,
    poster_path: "/yayzDar0dL3AvNoP1vPDFtinNYc.jpg",
    original_language: "en",
    original_title: "Charming",
    genre_ids: [16, 35, 10402],
    backdrop_path: "/gsfN0uKB3qwxU8oPJIFUNnrZho4.jpg",
    adult: false,
    overview:
      "Three fairy tale princesses find themselves engaged to the same guy, Prince Charming.",
    release_date: "2018-04-20"
  },
  {
    vote_count: 21,
    id: 434775,
    video: false,
    vote_average: 7,
    title: "The Third Murder",
    popularity: 4.367296,
    poster_path: "/jNKHZ5BWYTdUtfdHv4WAVoCWcxP.jpg",
    original_language: "ja",
    original_title: "三度目の殺人",
    genre_ids: [18, 9648, 80],
    backdrop_path: "/aEGSwp8SuiJPhheiIVNIXnebnlz.jpg",
    adult: false,
    overview:
      "Tomoaki Shigemori is a lawyer tasked with defending a client (Misumi), who faces the death penalty if found guilty, in a murder trial. Misumi has previous convictions for murder and has confessed to the crime, but evidence in the case leads to Shigemori having doubts about what really happened.",
    release_date: "2017-09-09"
  },
  {
    vote_count: 0,
    id: 495601,
    video: false,
    vote_average: 0,
    title: "A Rough Draft",
    popularity: 4.247183,
    poster_path: "/zY0O8aSjkexP4lgLbk6pGfB0Cyo.jpg",
    original_language: "ru",
    original_title: "Черновик",
    genre_ids: [878, 14],
    backdrop_path: null,
    adult: false,
    overview:
      'Young Muscovite Kirill is a talented designer of computer games. One day, he is completely erased from the memory of everyone he knew and loved. Kirill learns that he has been chosen for an important and mysterious mission: to become a customs officer between parallel worlds, of which there are dozens in the universe. Will Kirill unravel the mystery of these worlds and who controls them? And is our Earth really just an imaginary "draft" -- a parallel world -- which in reality does not exist ...',
    release_date: "2018-05-25"
  },
  {
    vote_count: 1,
    id: 499088,
    video: false,
    vote_average: 9,
    title: "Maya the Bee: The Honey Games",
    popularity: 3.923144,
    poster_path: "/aBfeHekIIjC4mFlark5MWJWDyZn.jpg",
    original_language: "en",
    original_title: "Maya the Bee: The Honey Games",
    genre_ids: [35, 10751],
    backdrop_path: "/e8IIrS4NksVOebS9YEQmzm7eJe0.jpg",
    adult: false,
    overview:
      "When an overenthusiastic Maya accidentally embarrasses the Empress of Buzztropolis, she is forced to unite with a team of misfit bugs and compete in the Honey Games for a chance to save her hive.",
    release_date: "2018-02-02"
  },
  {
    vote_count: 16,
    id: 470211,
    video: false,
    vote_average: 6.4,
    title: "Ami-Ami",
    popularity: 3.640423,
    poster_path: "/g4FQrHd24horEc3lyN2URDTTn9L.jpg",
    original_language: "fr",
    original_title: "Ami-Ami",
    genre_ids: [35],
    backdrop_path: "/yIb1ynPoT0Zd6DWXOj3RfgV6LXP.jpg",
    adult: false,
    overview: "",
    release_date: "2018-01-17"
  },
  {
    vote_count: 0,
    id: 511383,
    video: false,
    vote_average: 0,
    title: "Guppy",
    popularity: 2.439401,
    poster_path: "/4VCk8QJ68WM3zzhZ5O6AK8m2kgj.jpg",
    original_language: "ru",
    original_title: "Гупёшка",
    genre_ids: [18],
    backdrop_path: null,
    adult: false,
    overview:
      'One day, Tamara went out to throw out the garbage and met Pasha at the entrance with a bottle of wine and a desire to talk. After a visit, the man gets into the apartment of a new acquaintance, and she tells him how much she loves her husband Lenechka, who took her "rejected" from the village, planted her at home for a sewing machine and called "gupeshka" - in honor of an aquarium fish, submissive , silent, unwittingly devoted to the owner.',
    release_date: "2018-05-24"
  },
  {
    vote_count: 0,
    id: 518834,
    video: false,
    vote_average: 0,
    title: "Садко",
    popularity: 2.082754,
    poster_path: "/qVTkeSODoh7iIGIifBm3JuQKTYq.jpg",
    original_language: "ru",
    original_title: "Садко",
    genre_ids: [16, 35, 10751],
    backdrop_path: null,
    adult: false,
    overview: "",
    release_date: "2018-05-24"
  }
];

export default movies;
