export const moviesData = [
  {
    vote_count: 4592,
    id: 299536,
    video: false,
    vote_average: 8.5,
    title: "Avengers: Infinity War",
    popularity: 160.36938,
    poster_path: "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
    original_language: "en",
    original_title: "Avengers: Infinity War",
    backdrop_path: "/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg",
    adult: false,
    overview:
      "As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.",
    release_date: "2018-04-25"
  },
  {
    vote_count: 1410,
    id: 401981,
    video: false,
    vote_average: 6.4,
    title: "Red Sparrow",
    popularity: 58.167437,
    poster_path: "/vLCogyfQGxVLDC1gqUdNAIkc29L.jpg",
    original_language: "en",
    original_title: "Red Sparrow",
    backdrop_path: "/sGzuQYSTwJvLBc2PnuSVLHhuFeh.jpg",
    adult: false,
    overview:
      "Prima ballerina, Dominika Egorova faces a bleak and uncertain future after she suffers an injury that ends her career. She soon turns to Sparrow School, a secret intelligence service that trains exceptional young people to use their minds and bodies as weapons. Dominika emerges as the most dangerous Sparrow after completing the sadistic training process. As she comes to terms with her new abilities, she meets a CIA agent who tries to convince her that he is the only person she can trust.",
    release_date: "2018-03-01"
  },
  {
    vote_count: 29,
    id: 493922,
    video: false,
    vote_average: 6.7,
    title: "Hereditary",
    popularity: 36.915917,
    poster_path: "/wihYuMsQADWrSaVThaJunM2wR4V.jpg",
    original_language: "en",
    original_title: "Hereditary",
    backdrop_path: "/yVWiOMpzf7gullGvug83r7gMdha.jpg",
    adult: false,
    overview:
      "After their reclusive grandmother passes away, the Graham family tries to escape the dark fate they've inherited.",
    release_date: "2018-06-04"
  },
  {
    vote_count: 4,
    id: 260513,
    video: false,
    vote_average: 7.5,
    title: "Incredibles 2",
    popularity: 31.548805,
    poster_path: "/hL9Uz2vq93vi20oxZEBBaSs4w8U.jpg",
    original_language: "en",
    original_title: "Incredibles 2",
    backdrop_path: "/kqoBtMmiycbbhGLXGkKhL8SdaWB.jpg",
    adult: false,
    overview:
      "Elastigirl springs into action to save the day, while Mr. Incredible faces his greatest challenge yet – taking care of the problems of his three children.",
    release_date: "2018-06-14"
  },
  {
    vote_count: 42,
    id: 385332,
    video: false,
    vote_average: 5.6,
    title: "Terminal",
    popularity: 24.201971,
    poster_path: "/xi7pA3lL6Wb78p6Y6PgWoHDMjrM.jpg",
    original_language: "en",
    original_title: "Terminal",
    backdrop_path: "/bwvxvrHH3nTbcwpEcJhA72kkI94.jpg",
    adult: false,
    overview:
      "In the dark heart of a sprawling, anonymous city, two assassins carry out a sinister mission, a teacher battles a fatal illness, and an enigmatic janitor and a curious waitress lead dangerous double lives. Murderous consequences unravel in the dead of night, as their lives intertwine at the hands of a mysterious criminal mastermind who is hell-bent on revenge.",
    release_date: "2018-05-11"
  },
  {
    vote_count: 173,
    id: 396806,
    video: false,
    vote_average: 5.8,
    title: "Anon",
    popularity: 18.811023,
    poster_path: "/xhBTO9n3fxy3HJt7WlR9h9vvVmk.jpg",
    original_language: "en",
    original_title: "Anon",
    backdrop_path: "/arYvUXhpNRU2GQQut67P5cR0c5m.jpg",
    adult: false,
    overview:
      "Set in a near-future world where there is no privacy, ignorance or anonymity, our private memories are recorded and crime almost ceases to exist. In trying to solve a series of unsolved murders, Sal Frieland stumbles onto a young woman who appears to have subverted the system and disappeared. She has no identity, no history and no record. Sal realizes it may not be the end of crime but the beginning. Known only as 'The Girl', Sal must find her before he becomes the next victim.",
    release_date: "2018-05-03"
  },
  {
    vote_count: 41,
    id: 454619,
    video: false,
    vote_average: 5.6,
    title: "Overboard",
    popularity: 18.502901,
    poster_path: "/qauHzSQJdo9VYX4NKn9PdWnvXOV.jpg",
    original_language: "en",
    original_title: "Overboard",
    backdrop_path: "/6PQyCsluWxE0LPlp2YB6IkMqVQj.jpg",
    adult: false,
    overview:
      "A spoiled, wealthy yacht owner is thrown overboard and becomes the target of revenge from his mistreated employee. A remake of the 1987 comedy.",
    release_date: "2018-05-03"
  },
  {
    vote_count: 21,
    id: 411135,
    video: false,
    vote_average: 5.8,
    title: "Future World",
    popularity: 17.779676,
    poster_path: "/kMA0IalnEEa0PaHRUzzjpTu5xXQ.jpg",
    original_language: "en",
    original_title: "Future World",
    backdrop_path: "/g29nhwmOiYElKW27hzohK6nSwpC.jpg",
    adult: false,
    overview:
      "A young boy searches a future world wasteland for a rumored cure for his dying mother.",
    release_date: "2018-05-25"
  },
  {
    vote_count: 467,
    id: 399174,
    video: false,
    vote_average: 7.9,
    title: "Isle of Dogs",
    popularity: 17.693788,
    poster_path: "/c0nUX6Q1ZB0P2t1Jo6EeFSVnOGQ.jpg",
    original_language: "en",
    original_title: "Isle of Dogs",
    backdrop_path: "/5YtXsLG9ncjjFyGZjoeV31CGf01.jpg",
    adult: false,
    overview:
      "In the future, an outbreak of canine flu leads the mayor of a Japanese city to banish all dogs to an island that's a garbage dump. The outcasts must soon embark on an epic journey when a 12-year-old boy arrives on the island to find his beloved pet.",
    release_date: "2018-03-23"
  },
  {
    vote_count: 43,
    id: 341689,
    video: false,
    vote_average: 5.7,
    title: "How to Talk to Girls at Parties",
    popularity: 14.513143,
    poster_path: "/v6mPfyGshwXd1R6kQlMEyZ8Zu2s.jpg",
    original_language: "en",
    original_title: "How to Talk to Girls at Parties",
    backdrop_path: "/hjUkiNj0IWGym554fQs0Gnx4XZG.jpg",
    adult: false,
    overview:
      "A couple of British 1970s teenaged boys, Enn and Vic, go to a party to meet girls, only to find that the girls are very different from the boys' expectations.",
    release_date: "2018-05-05"
  },
  {
    vote_count: 25,
    id: 332283,
    video: false,
    vote_average: 6.6,
    title: "Mary Shelley",
    popularity: 13.8451,
    poster_path: "/gKHJTsrfxJtfFNPQJn2hDNEMtFf.jpg",
    original_language: "en",
    original_title: "Mary Shelley",
    backdrop_path: "/3vp5dMXAzbl5JUoGgVXEBZMJn7i.jpg",
    adult: false,
    overview:
      "The love affair between poet Percy Shelley and Mary Wollstonecraft Godwin resulted in the creation of an immortal novel, “Frankenstein; or, The Modern Prometheus.”",
    release_date: "2018-04-22"
  },
  {
    vote_count: 148,
    id: 437557,
    video: false,
    vote_average: 6.3,
    title: "Blockers",
    popularity: 13.458385,
    poster_path: "/cx0LpfM6Drla8uzFfMT09uqKPRu.jpg",
    original_language: "en",
    original_title: "Blockers",
    backdrop_path: "/fqPIDVSTl6f1l02fb2rRVYPl5JE.jpg",
    adult: false,
    overview:
      "When three parents discover their daughters’ pact to lose their virginity at prom, they launch a covert one-night operation to stop the teens from sealing the deal.",
    release_date: "2018-03-30"
  },
  {
    vote_count: 118,
    id: 425336,
    video: false,
    vote_average: 6.3,
    title: "Loving Pablo",
    popularity: 12.199422,
    poster_path: "/6McYL1YZmRSeccDXxpFNslUw2c5.jpg",
    original_language: "es",
    original_title: "Loving Pablo",
    backdrop_path: "/qbAwhPUhzHMofSbV5GpeAFrb6pg.jpg",
    adult: false,
    overview:
      "A journalist strikes up a romantic relationship with notorious drug lord Pablo Escobar.",
    release_date: "2018-03-09"
  },
  {
    vote_count: 54,
    id: 460668,
    video: false,
    vote_average: 6.3,
    title: "I Feel Pretty",
    popularity: 12.146981,
    poster_path: "/bZe6x2fKtwVDsAvZQ9fnIJznBrc.jpg",
    original_language: "en",
    original_title: "I Feel Pretty",
    backdrop_path: "/7XM7kxa3U2g8TO3OGSiETCroNRD.jpg",
    adult: false,
    overview:
      "A head injury causes a woman to develop an extraordinary amount of confidence and believe she's drop dead gorgeous.",
    release_date: "2018-04-20"
  },
  {
    vote_count: 822,
    id: 411088,
    video: false,
    vote_average: 8.2,
    title: "The Invisible Guest",
    popularity: 11.070862,
    poster_path: "/fptnZJbLzKUHeNlYrAynbyoL5YJ.jpg",
    original_language: "es",
    original_title: "Contratiempo",
    backdrop_path: "/urrIaUxmLXYWodZx7KJPLLVFaKC.jpg",
    adult: false,
    overview:
      "'The Invisible Guest' turns on a young businessman who wakes up in a hotel room locked from the inside with the dead body of his lover next to him. He hires a prestigious lawyer, and over one night they work together to clarify what happened in a frenetic race against time.",
    release_date: "2016-09-22"
  },
  {
    vote_count: 0,
    id: 519033,
    video: false,
    vote_average: 0,
    title: "Sobchak Case",
    popularity: 10.512537,
    poster_path: "/vrBNIeetvYXeqCoXWSIoW1jT1tQ.jpg",
    original_language: "ru",
    original_title: "Дело Собчака",
    backdrop_path: "/pU5c029oAV7WQND202vYt0ldeUI.jpg",
    adult: false,
    overview:
      "After the father’s death, the daughter of one of the forefathers of modern Russian democracy, Ksenia Sobchak, tries to understand the 18 years of his political fate. Together with the director Vera Krichevskaya she gives the word to Anatoli Sobchak’s colleagues and opponents, gets acquainted with the criminal case which annulled his career, and tries to find an answer to the question what Anatoly Sobchak’s fate would be in today’s Russia.",
    release_date: "2018-06-12"
  },
  {
    vote_count: 15,
    id: 425148,
    video: false,
    vote_average: 5.8,
    title: "Show Dogs",
    popularity: 9.86842,
    poster_path: "/2dvxCBUfDG2cAdkA921rERxhtcp.jpg",
    original_language: "en",
    original_title: "Show Dogs",
    backdrop_path: "/pk1zexoUCtjFs761W48QyIPzwCj.jpg",
    adult: false,
    overview:
      "Max, a macho, solitary Rottweiler police dog is ordered to go undercover as a primped show dog in a prestigious Dog Show, along with his human partner, to avert a disaster from happening.",
    release_date: "2018-05-10"
  },
  {
    vote_count: 0,
    id: 517745,
    video: false,
    vote_average: 0,
    title: "The First",
    popularity: 9.829438,
    poster_path: "/scSLVsmQdD6kVFYskp84gYLpX5M.jpg",
    original_language: "ru",
    original_title: "Первые",
    backdrop_path: "/ecHD0rmx8l4eZVSISLJVAgAaODU.jpg",
    adult: false,
    overview:
      "Vasily Pronchishchev and Vasily Chelyuskin were young lieutenants of the Russia fleet, who set out from Yakutsk along the Lena River to the Arctic Ocean on a sailing ship under the leadership of the commander Vitus Bering in the summer of 1735. Contrary to the imperial prohibition, incredible trials and deadly danger lying ahead of all the members of this expedition, a young girl enamored with one of the characters got onto this ship. However, neither storms or severe northern frosts and hunger were able to stop them, since fulfilling of their duty, reaching of the most northeastern point of Eurasia and putting of the vast Arctic territories on the world maps were their main purpose in life.",
    release_date: "2018-06-07"
  },
  {
    vote_count: 2,
    id: 502897,
    video: false,
    vote_average: 0,
    title: "Leto",
    popularity: 8.567759,
    poster_path: "/syl3gKnmGEmV20ObA8JHxPU8RvQ.jpg",
    original_language: "ru",
    original_title: "Лето",
    backdrop_path: "/eFod8dTZVH3SFDF13V5ls2Hb00W.jpg",
    adult: false,
    overview:
      "Leningrad, one summer in the early eighties. Smuggling LP’s by Lou Reed and David Bowie, the underground rock scene is boiling ahead of the Perestroika. Mike and his beautiful wife Natasha meet with young Viktor Tsoï. Together with friends, they will change the destiny of rock’n’roll in the Soviet Union.",
    release_date: "2018-06-07"
  },
  {
    vote_count: 5,
    id: 440626,
    video: false,
    vote_average: 5.8,
    title: "Sobibor",
    popularity: 8.662257,
    poster_path: "/rGOB5Xm0l0zAWAzVzeTnOPDMVQA.jpg",
    original_language: "ru",
    original_title: "Собибор",
    backdrop_path: "/5KhMpFJdnOAsDmIpT0TINUNDt8L.jpg",
    adult: false,
    overview:
      "Based on the true story, international historical project “Sobibor” is dedicated to the heroism of the Soviet o cer Alexander Pechersky. During the great Patriotic war, being in a Nazi concentration camp Sobibor he managed to do the impossible — for only three weeks to organize a revolt and mass escape of the prisoners. Part of the escapees were caught and shot, and the rest led by Pechersky managed to escape and joined the partisans.",
    release_date: "2018-05-03"
  }
];